name: nordic_dfu_web
description: A new flutter plugin project.
version: 0.0.1
homepage: https://github.com/rohitsangwan01/nordic_dfu_web.git
repository: https://github.com/rohitsangwan01/nordic_dfu_web.git

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: NordicDfuWebWeb
        fileName: nordic_dfu_web_web.dart
